services:
  event-ingest:
    build:
      context: ../services/event-ingest
      dockerfile: Dockerfile
    container_name: shop-event-ingest
    ports:
      - "8080:8080"
    volumes:
      - ../shared:/shared
    networks:
      - network1

    depends_on:
      - mysql-pipeline