services:
  mysql-shard-0:
    image: mysql:8.0
    container_name: shop-mysql-shard-0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_shard_0
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3306:3306"
    volumes:
      - ../db/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - mysql_shard_0_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mysql-shard-1:
    image: mysql:8.0
    container_name: shop-mysql-shard-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_shard_1
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3307:3306"
    volumes:
      - ../db/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - mysql_shard_1_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mysql-pipeline:
    image: mysql:8.0
    container_name: shop-mysql-pipeline
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pipeline_db
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3308:3306"
    volumes:
      - ../db/pipeline_ddl.sql:/docker-entrypoint-initdb.d/01-pipeline-ddl.sql
      - mysql_pipeline_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_shard_0_data:
  mysql_shard_1_data:
  mysql_pipeline_data:
