services:
  shard-splitter:
    build:
      context: ../services/shard-splitter
      dockerfile: Dockerfile
    container_name: shop-shard-splitter
    volumes:
      - ../shared:/shared

    ports:
      - "8082:8082"

    networks:
      - network1

    depends_on:
      - mysql-pipeline

networks:
  network1:
    driver: bridge