[package]
name = "shard-splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "mysql"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"